# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseTitle', models.CharField(max_length=255)),
                ('DOJ', models.DateField()),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MentionedIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cases3', to='toy.Cases')),
                ('mentioned_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cases4', to='toy.Cases')),
            ],
        ),
        migrations.CreateModel(
            name='Mentions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cases1', to='toy.Cases')),
                ('mentions_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cases2', to='toy.Cases')),
            ],
        ),
    ]
