# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='caseTitle',
            field=models.CharField(max_length=10),
        ),
    ]
